language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*@dev
    - SYMFONY_VERSION="3.0.x-dev as 2.8"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - phpunit --coverage-text

notifications:
  email: yann.eugone@gmail.com
